const Actions={
    GET_ALL_FILMS:'GET_ALL_FILMS',
    SET_CURRENT_FILM:'SET_CURRENT_FILM',
    SET_CURRENT_PLANET:'SET_CURRENT_PLANET',
    SET_CURRENT_STARSHIP:'SET_CURRENT_STARSHIP',
    SET_CURRENT_ITEM:'SET_CURRENT_ITEM',
    GET_ITEM_INFO_BY_LINK:'GET_ITEM_INFO_BY_LINK',
    SET_CURRENT_ITEM_FORCED:'SET_CURRENT_ITEM_FORCED'
}
export default Actions