const Actions={
    GET_ALL_FILMS:'GET_ALL_FILMS',
    SET_CURRENT_FILM:'SET_CURRENT_FILM',
    SET_CURRENT_PLANET:'SET_CURRENT_PLANET',
    SET_CURRENT_STARSHIP:'SET_CURRENT_STARSHIP',
    GET_ITEM_INFO_BY_LINK:'GET_ITEM_INFO_BY_LINK'
}
export default Actions