const Actions={
    GET_ALL_FILMS:'GET_ALL_FILMS',
    SET_CURRENT_ITEM:'SET_CURRENT_ITEM',
    GET_ITEM_INFO_BY_LINK:'GET_ITEM_INFO_BY_LINK',
    SET_CURRENT_ITEM_FORCED:'SET_CURRENT_ITEM_FORCED',
    GET_SEARCHED_FILMS:'GET_SEARCHED_FILMS',
    SET_SEARCHED_FILMS_TO_NULL:'SET_SEARCHED_FILMS_TO_NULL'
}
export default Actions